name: 01-Try out

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: printing welome to github worklow
        run: echo "Hello welcome to github Actions"
      - name: multiline
        run: |
          echo "line 1"
          echo "line 2"
          echo "line 3"
