name: CI-CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  NODE_VERSION: "22"
  IMAGE_NAME: sample-app

jobs:

  # ==========================================
  # 1. TEST
  # ==========================================
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: 'sample-app/package-lock.json'

      - name: Install dependencies
        working-directory: ./sample-app
        run: npm ci

      - name: Run tests
        working-directory: ./sample-app
        run: npm test
